### ISSUE TITLE
filter_telomere_reads

### ISSUE THREAD

**Issue by tanasa** [cancerit/telomerehunter-docker#5]
Hi. 

I have installed telomerehunter with pip. I am running the python file "telomerehunter" and I am getting an error. 
Would you please let me know how I could fix it ? Thank you very much :) !

_Traceback (most recent call last):
  File "/home/tanasab/.local/bin/telomerehunter", line 31, in <module>
    import telomerehunter
  File "/home/tanasab/.local/lib/python3.8/site-packages/telomerehunter/__init__.py", line 2, in <module>
    import filter_telomere_reads
ModuleNotFoundError: No module named 'filter_telomere_reads'_

**Comment by davidrajones** [comment]
Hi @tanasa 

This project is to provide a docker image to wrap telomerehunter. Telomerehunter code itself is found [here](https://www.dkfz.de/en/applied-bioinformatics/telomerehunter/telomerehunter.html) 

To avoid installing telomerehunter you could use our [docker image](https://quay.io/repository/wtsicgp/cgp-telomerehunter) or please contact the code owners for instructions on installation.
