### ISSUE TITLE
Issue with Docker Image - ggplot2 not found

### ISSUE THREAD

**Issue by szabolcstarapcsak** [cancerit/telomerehunter-docker#6]
Hi!

I have been using TelomereHunter Docker Image to analyze telomeric sequences in cancer cell lines and it was working perfectly. However, in the last couple of days my runs end always with the same error message: 

* removing '/usr/local/lib/R/site-library/Hmisc'
ERROR: dependencies 'htmltools', 'lifecycle', 'rlang', 'testthat', 'xml2' are not available for package 'vdiffr'
* removing '/usr/local/lib/R/site-library/vdiffr'

The downloaded source packages are in
	'/tmp/Rtmp9LV651/downloaded_packages'
Loading required package: ggplot2
Error in pkgTest(library) : R Package" ggplot2 "not found
In addition: There were 38 warnings (use warnings() to see them)
Execution halted

Could you please provide me with some information what is the reason for my issues with ggplot2?
Thank you, Szabi

**Comment by davidrajones** [comment]
Hi @szabolcstarapcsak 

Firstly could I ask what commandline you are using to run telomerehunter please? This looks more like R is looking for local packages than missing them in the Docker image.

**Comment by AndyMenzies** [comment]
Closed due to no response

**Comment by gbnci** [comment]
Hello:
Recently I am trying to use telomerehunter-docker container, most parts of the software work fine except the plotting step. I am using HPC system under "sinteractive" for the testing run. my command line is something similar like below:

singularity exec --cleanenv --workdir /data/wangyong/telomere/telomerehunter \
--home /data/wangyong/telomere/telomerehunter:/home \
--bind /data/CCRBioinfo/projects/TargetOsteo_studies/TargetOsteoDiscoveryWGS/bam:/var/spool/data \
--bind /data/wangyong/telomere/telomerehunter/AAA:/var/spool/results \
telomerehunter_latest.sif \
telomerehunter \
-ibt /var/spool/data/AAA_Tumor.final.bam \
-ibc /var/spool/data/AAA_Normal.final.bam \
-p AAA \
-o /var/spool/results

The error I got is:
------ making plots ------
Loading required package: ggplot2
Installing package into '/usr/local/lib/R/site-library'
(as 'lib' is unspecified)
Warning in install.packages(x, dep = TRUE) :
  'lib = "/usr/local/lib/R/site-library"' is not writable
Error in install.packages(x, dep = TRUE) : unable to install packages
Calls: pkgTest -> install.packages
In addition: Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called 'ggplot2'
Execution halted
[ERROR] Failed to install required R library.

This error is quite similar to this "closed" issue, I am wondering whether you can give me some suggestions to take care of this problem? By the way, telomerehunter has indeed generated all text related files but quit when doing the plot.

Thanks
YH

**Comment by szabolcstarapcsak** [comment]
Hi @davidrajones !

Sorry for my late answer. I used the following code to run TelomereHunter.

export DIR=/home/szabolcs_tarapcsak_work_dir/sra
export BAM=U2OS_WGS.bam
sudo docker run -d -P --name telomerehunter1 -v $DIR:/home/docker erictdawson/telomerehunter telomerehunter -ibt /home/docker/$BAM -o /home/docker -p U2OS

Another thing I realized that after running this command on tumor/normal sample pairs the TVR folder was not created and neither the  *_normalized_TVR_counts.tsv file, mentioned in the description of TelomereHunter (https://www.dkfz.de/en/applied-bioinformatics/telomerehunter/telomerehunter.html). Do you have any idea why? Thank you!

@gbnci I have found the R scripts for making the plots. After I ran TelomereHunter on my VM I downloaded the output files and plotted them on my local machine. Let me know if you have any questions.

Szabi

**Comment by gbnci** [comment]
@szabolcstarapcsak 
Thank you very much for your quick response. Just wondering whether you can share the R scripts for the plotting or let me know where to find them. Appreciated for your help
YH

**Comment by gbnci** [comment]
@szabolcstarapcsak
Don't worry about my previous message. I found all the R scripts and everything should be fine now. 
Thanks
YH

**Comment by szabolcstarapcsak** [comment]
Awesome! 
Best, Szabi
